workflows:
  android-production-build:
    name: Android Production Build - Supplier App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    scripts:
      - name: Install Mobile App Dependencies
        script: |
          cd mobile-app
          npm ci --legacy-peer-deps
          # Ensure expo is installed locally (not hoisted)
          npm install expo@~50.0.0 --save --legacy-peer-deps
          # Install @expo/config-plugins for SDK 50 compatibility
          npm install @expo/config-plugins@^7.8.0 --save-dev --legacy-peer-deps
          # Fix ajv dependency issue (required by ajv-keywords)
          npm install ajv@^8.12.0 --save-dev --legacy-peer-deps || true
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
          
      - name: Fix Dependencies
        script: |
          cd mobile-app
          npx expo install --fix
          
      - name: Prebuild Android
        script: |
          cd mobile-app
          rm -rf android
          npx expo prebuild --platform android --clean
          
      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon --stacktrace
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
