workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
      java: 17
    scripts:
      - name: Install mobile-app dependencies
        script: |
          cd mobile-app
          # Install dependencies without workspace hoisting
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Verify expo-build-properties installation
        script: |
          cd mobile-app
          # Ensure expo-build-properties is in mobile-app/node_modules
          if [ ! -d "node_modules/expo-build-properties" ]; then
            echo "⚠️ expo-build-properties not found, installing..."
            npm install expo-build-properties@~0.12.5
          else
            echo "✅ expo-build-properties found in correct location"
          fi
          
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
          
      - name: Fix ExpoModulesCorePlugin Gradle Error
        script: |
          cd mobile-app
          
          # Debug: Show what's in expo-modules-core
          echo "Checking expo-modules-core installation..."
          if [ -d "node_modules/expo-modules-core" ]; then
            echo "✅ expo-modules-core found"
            echo "Contents of android directory:"
            ls -la node_modules/expo-modules-core/android/ 2>/dev/null || echo "android directory not found"
          else
            echo "⚠️ expo-modules-core not found in node_modules"
          fi
          
          PLUGIN_FILE="node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
          
          if [ -f "$PLUGIN_FILE" ]; then
            echo "Patching $PLUGIN_FILE line 76..."
            echo "Original line 76:"
            sed -n '76p' "$PLUGIN_FILE"
            
            # Use perl for more reliable replacement on macOS
            perl -i -pe 's/components\.release/components.getByName("release")/g' "$PLUGIN_FILE"
            perl -i -pe 's/components\["release"\]/components.getByName("release")/g' "$PLUGIN_FILE"
            
            echo "After patching line 76:"
            sed -n '76p' "$PLUGIN_FILE"
            echo "✅ Patched successfully"
          else
            echo "⚠️ Plugin file not found - skipping patch"
            echo "This is OK if expo-build-properties handles SDK versions correctly"
          fi
          
      - name: Patch All Expo Modules
        script: |
          cd mobile-app
          echo "🔧 Removing useDefaultAndroidSdkVersions() from all Expo modules..."
          
          # List all expo modules first
          ls -d node_modules/expo-*/android 2>/dev/null || echo "No expo modules found"
          
          # Find and patch all expo-*/android/build.gradle files using perl
          find node_modules -path "*/expo-*/android/build.gradle" -type f 2>/dev/null | while read file; do
            if grep -q "useDefaultAndroidSdkVersions()" "$file"; then
              echo "Found in: $file"
              echo "Before:"
              grep -n "useDefaultAndroidSdkVersions" "$file"
              
              # Remove the line using perl (more reliable on macOS)
              perl -i -pe 's/.*useDefaultAndroidSdkVersions\(\).*\n//g' "$file"
              
              echo "After patch - verifying removal:"
              if grep -q "useDefaultAndroidSdkVersions" "$file"; then
                echo "⚠️ Still exists, trying alternative method"
                # Comment it out instead
                perl -i -pe 's/(.*useDefaultAndroidSdkVersions.*)$/\/\/ $1 \/\/ REMOVED/g' "$file"
              fi
              echo "✅ Patched: $file"
            fi
          done
          
          # Verify no instances remain
          echo "Verification - checking for remaining instances:"
          if find node_modules -path "*/expo-*/android/build.gradle" -type f -exec grep -l "useDefaultAndroidSdkVersions()" {} \; 2>/dev/null; then
            echo "⚠️ Warning: Some instances still found"
          else
            echo "✅ All instances removed successfully"
          fi
          
      - name: Set Gradle Permissions
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
      - name: Build APK
        script: |
          cd mobile-app/android
          ./gradlew assembleRelease --stacktrace --info
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
