workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    scripts:
      - name: Install Dependencies & Fix Versions
        script: |
          cd mobile-app
          # Install current package.json dependencies
          npm install --legacy-peer-deps
          
          # Force update Expo dependencies to match SDK 51 requirements
          # This fixes the expo-modules-core incompatibility by pulling the latest patch version
          echo "🔧 Fixing Expo dependency versions..."
          npx expo install --fix
          
          # Verify expo-modules-core version
          echo "📦 Checked expo-modules-core version:"
          npm list expo-modules-core
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild ensures fresh config
          npx expo prebuild --platform android --clean
          
          # Verify plugin is available via settings.gradle
          if [ -f "android/settings.gradle" ]; then
            echo "Checking settings.gradle for expo-modules-core..."
            if grep -q "expo-modules-core" android/settings.gradle; then
              echo "✅ expo-modules-core found in settings.gradle"
            else
              echo "⚠️ expo-modules-core NOT found in settings.gradle"
              echo "expo prebuild should have added autolinking"
              echo "First 50 lines of settings.gradle:"
              head -50 android/settings.gradle
            fi
          fi
          
          # Verify expo-modules-core is installed
          if [ ! -d "node_modules/expo-modules-core" ]; then
            echo "❌ expo-modules-core not installed!"
            npm install expo-modules-core@~1.12.0
          fi
          
          # Check if gradle-plugin directory exists
          if [ ! -d "node_modules/expo-modules-core/android/gradle-plugin" ]; then
            echo "❌ gradle-plugin directory not found!"
            echo "Reinstalling expo-modules-core..."
            npm install expo-modules-core@~1.12.0 --force
          else
            echo "✅ gradle-plugin directory exists"
          fi
          
          # Ensure plugin is available via included build in settings.gradle
          if [ -f "android/settings.gradle" ] && [ -d "node_modules/expo-modules-core/android/gradle-plugin" ]; then
            echo "Ensuring plugin is registered via included build..."
            
            # Check if included build is already there
            if ! grep -q "includeBuild.*expo-modules-core.*gradle-plugin" android/settings.gradle; then
              echo "Adding included build for expo-module-gradle-plugin..."
              
              # Get relative path to gradle-plugin
              PLUGIN_PATH=$(node -e "
                const path = require('path');
                const androidDir = path.resolve('android');
                const pluginPath = path.resolve('node_modules/expo-modules-core/android/gradle-plugin');
                const relative = path.relative(androidDir, pluginPath);
                console.log(relative);
              " 2>/dev/null || echo "../node_modules/expo-modules-core/android/gradle-plugin")
              
              # Add included build at the end of settings.gradle
              printf '\n// Expo module gradle plugin\n' >> android/settings.gradle
              printf "includeBuild('$PLUGIN_PATH')\n" >> android/settings.gradle
              
              echo "✅ Added included build for plugin"
            else
              echo "✅ Included build already present"
            fi
          fi
          
          # Verify buildscript
          if [ -f "android/build.gradle" ]; then
            echo "Buildscript section:"
            grep -A 20 "buildscript" android/build.gradle | head -25
          fi
          
      - name: Patch Expo Modules Core (Targeted Root Fix)
        script: |
          # Define the specific path where the error is occurring (Root of the repo)
          TARGET_FILE="$CM_BUILD_DIR/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
          
          echo "📝 Targeted Patching of: $TARGET_FILE"
          
          if [ -f "$TARGET_FILE" ]; then
            echo "✅ Found file at root!"
            # create backup
            cp "$TARGET_FILE" "$TARGET_FILE.backup"
            # Comment out line 85 (or any line matching the buggy code)
            sed -i.bak 's/from components.release/\/\/ from components.release \/\/ PATCHED BY CI/g' "$TARGET_FILE"
            echo "✅ Patched file successfully"
            grep "PATCHED BY CI" "$TARGET_FILE"
          else
            echo "❌ File not found at expected path: $TARGET_FILE"
            echo "Listing root node_modules/expo-modules-core to debug:"
            ls -R "$CM_BUILD_DIR/node_modules/expo-modules-core" || echo "Dir not found"
            exit 1
          fi
          
          # Also check mobile-app just in case
          TARGET_FILE_LOCAL="$CM_BUILD_DIR/mobile-app/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
          if [ -f "$TARGET_FILE_LOCAL" ]; then
             echo "🔧 Also patching local instance: $TARGET_FILE_LOCAL"
             sed -i.bak 's/from components.release/\/\/ from components.release \/\/ PATCHED BY CI/g' "$TARGET_FILE_LOCAL"
          fi
          
      - name: Build Android APK (Gradle)
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build..."
          
          # Run build using Gradle wrapper
          ./gradlew assembleRelease --no-daemon --stacktrace
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
