workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/mobile-app/node_modules
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install Dependencies
        script: |
          cd mobile-app
          # Use npm install since package-lock.json might be missing
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild to ensure new Gradle config is generated
          npx expo prebuild --platform android --clean
          
      - name: Patch expo-modules-core bug (line 85)
        script: |
          cd mobile-app
          
          echo "📝 Patching ExpoModulesCorePlugin.gradle to fix 'release' property bug..."
          
          # Debug: Check current directory and node_modules
          echo "Current directory: $(pwd)"
          echo "Checking for node_modules..."
          ls -la | grep node_modules || echo "node_modules not found in current dir"
          
          # Try to find the file
          echo "Searching for ExpoModulesCorePlugin.gradle..."
          find . -name "ExpoModulesCorePlugin.gradle" -type f 2>/dev/null || echo "File not found anywhere"
          
          PLUGIN_FILE="node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
          
          if [ ! -f "$PLUGIN_FILE" ]; then
            echo "❌ Plugin file not found at: $PLUGIN_FILE"
            echo "Trying alternate path..."
            # Maybe it's in the root?
            cd ..
            PLUGIN_FILE="mobile-app/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
            if [ ! -f "$PLUGIN_FILE" ]; then
              echo "❌ Still not found!"
              exit 1
            fi
          fi
          
          echo "✅ Found plugin file at: $PLUGIN_FILE"
          
          # Backup original
          cp "$PLUGIN_FILE" "$PLUGIN_FILE.backup"
          
          # Comment out the buggy line 85
          sed -i.bak '85s/.*/                \/\/ from components.release \/\/ PATCHED: incompatible with Gradle 8.x/' "$PLUGIN_FILE"
          
          echo "✅ Patched expo-modules-core plugin"
          echo "Line 85 is now:"
          sed -n '85p' "$PLUGIN_FILE"
          
      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build (SDK 51 + Gradle 8)..."
          
          # Capture both stdout and stderr to log file
          ./gradlew assembleRelease --no-daemon --stacktrace --info > build.log 2>&1
          BUILD_EXIT_CODE=$?
          
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo ""
            echo "❌ BUILD FAILED! AUTOMATIC ERROR REPORT:"
            echo "=============================================================================="
            echo "Build exit code: $BUILD_EXIT_CODE"
            echo "Log file size: $(wc -c < build.log) bytes"
            echo "Log file lines: $(wc -l < build.log) lines"
            echo ""
            
            # Always show the last 150 lines
            echo "Last 150 lines of build output:"
            tail -n 150 build.log
            
            echo "=============================================================================="
            exit 1
          fi
          
          echo "✅ Build succeeded!"
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
      - mobile-app/android/build.log
