workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/mobile-app/node_modules
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install Dependencies
        script: |
          cd mobile-app
          # Use npm install since package-lock.json might be missing
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild to ensure new Gradle config is generated
          npx expo prebuild --platform android --clean
          
      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build (SDK 51 + Gradle 8)..."
          
          # Use pipefail to catch build errors through tee
          set -o pipefail
          
          if ! ./gradlew assembleRelease --no-daemon --stacktrace --info | tee build.log; then
            echo ""
            echo "❌ BUILD FAILED! AUTOMATIC ERROR REPORT:"
            echo "=============================================================================="
            
            # Try to find the standard Gradle error block
            if grep -q "What went wrong:" build.log; then
              echo "Found 'What went wrong' section:"
              grep -B 2 -A 20 "What went wrong:" build.log
            else
              echo "No 'What went wrong' found. Showing last 100 lines of log:"
              tail -n 100 build.log
            fi
            
            echo "=============================================================================="
            exit 1
          fi
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
      - mobile-app/android/build.log
