workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Fix dependencies
        script: |
          cd mobile-app
          npx expo install --fix
      - name: Install expo-modules-core
        script: |
          cd mobile-app
          npm install expo-modules-core@~1.11.0
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
      - name: Fix Expo Module Plugin
        script: |
          cd mobile-app
          # Verify expo-modules-core is installed
          if [ ! -d "node_modules/expo-modules-core/android" ]; then
            echo "Installing expo-modules-core..."
            npm install expo-modules-core@~1.11.0
          fi
          echo "âœ… expo-modules-core verified"
          
      - name: Patch ALL Expo Modules Gradle Files
        script: |
          echo "ðŸ”§ Patching ALL Expo modules to remove useDefaultAndroidSdkVersions()..."
          
          # Function to patch a file
          patch_file() {
            local file="$1"
            if [ -f "$file" ]; then
              echo "Patching: $file"
              # Remove the problematic line
              sed -i '' '/useDefaultAndroidSdkVersions()/d' "$file"
              # Add SDK versions if missing
              if ! grep -q "compileSdkVersion" "$file"; then
                sed -i '' '/android {/a\
          compileSdkVersion 34\
          buildToolsVersion "34.0.0"' "$file"
              fi
              echo "âœ… Patched: $file"
            fi
          }
          
          # Find and patch ALL expo-* modules in all locations
          echo "Searching for all expo modules..."
          
          # Search in current directory
          find . -type f -path "*/expo-*/android/build.gradle" 2>/dev/null | while read file; do
            patch_file "$file"
          done
          
          # Search in mobile-app
          if [ -d "mobile-app" ]; then
            find mobile-app -type f -path "*/expo-*/android/build.gradle" 2>/dev/null | while read file; do
              patch_file "$file"
            done
          fi
          
          # Search in clone directory (Codemagic's working directory)
          if [ -d "/Users/builder/clone" ]; then
            find /Users/builder/clone -type f -path "*/expo-*/android/build.gradle" 2>/dev/null | while read file; do
              patch_file "$file"
            done
          fi
          
          # Also check common problematic modules explicitly
          for module in expo-asset expo-file-system expo-camera expo-location expo-sharing expo-constants; do
            for base in "." "mobile-app" "/Users/builder/clone"; do
              file="$base/node_modules/$module/android/build.gradle"
              patch_file "$file"
            done
          done
          
          echo "âœ… Finished patching all Expo modules"
          
      - name: Final Comprehensive Gradle Patch Before Build
        script: |
          echo "ðŸ”§ Final comprehensive patch - removing useDefaultAndroidSdkVersions() from ALL expo modules..."
          
          # Find and patch ALL expo-* modules one more time before build
          find . -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' '/useDefaultAndroidSdkVersions()/d' {} \;
          
          if [ -d "mobile-app" ]; then
            find mobile-app -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' '/useDefaultAndroidSdkVersions()/d' {} \;
          fi
          
          if [ -d "/Users/builder/clone" ]; then
            find /Users/builder/clone -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' '/useDefaultAndroidSdkVersions()/d' {} \;
          fi
          
          # Verify - count remaining instances
          remaining=$(find . mobile-app /Users/builder/clone -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec grep -l "useDefaultAndroidSdkVersions()" {} \; 2>/dev/null | wc -l | tr -d ' ')
          if [ "$remaining" -gt 0 ]; then
            echo "âš ï¸ Warning: Still found $remaining files with useDefaultAndroidSdkVersions()"
            echo "Trying alternative method - commenting out..."
            find . -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' 's/useDefaultAndroidSdkVersions()/\/\/ useDefaultAndroidSdkVersions() - removed/g' {} \;
            if [ -d "mobile-app" ]; then
              find mobile-app -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' 's/useDefaultAndroidSdkVersions()/\/\/ useDefaultAndroidSdkVersions() - removed/g' {} \;
            fi
            if [ -d "/Users/builder/clone" ]; then
              find /Users/builder/clone -type f -path "*/expo-*/android/build.gradle" 2>/dev/null -exec sed -i '' 's/useDefaultAndroidSdkVersions()/\/\/ useDefaultAndroidSdkVersions() - removed/g' {} \;
            fi
          else
            echo "âœ… Verified: All useDefaultAndroidSdkVersions() removed"
          fi
          
      - name: Build APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk

