workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
      java: 17
    scripts:
      - name: Install mobile-app dependencies
        script: |
          cd mobile-app
          # Install dependencies without workspace hoisting
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Verify expo-build-properties installation
        script: |
          cd mobile-app
          # Ensure expo-build-properties is in mobile-app/node_modules
          if [ ! -d "node_modules/expo-build-properties" ]; then
            echo "âš ï¸ expo-build-properties not found, installing..."
            npm install expo-build-properties@~0.12.5
          else
            echo "âœ… expo-build-properties found in correct location"
          fi
          
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
          
      - name: Fix ExpoModulesCorePlugin Gradle Error
        script: |
          cd mobile-app
          PLUGIN_FILE="node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle"
          
          if [ -f "$PLUGIN_FILE" ]; then
            echo "Patching $PLUGIN_FILE line 76..."
            
            # Create a backup
            cp "$PLUGIN_FILE" "${PLUGIN_FILE}.backup"
            
            # Fix line 76 - replace .release with .getByName("release")
            sed -i.bak 's/components\.release/components.getByName("release")/g' "$PLUGIN_FILE"
            sed -i.bak 's/components\["release"\]/components.getByName("release")/g' "$PLUGIN_FILE"
            
            # Remove backup file created by sed
            rm -f "${PLUGIN_FILE}.bak"
            
            echo "âœ… Patched successfully"
            echo "Showing line 76:"
            sed -n '76p' "$PLUGIN_FILE"
          else
            echo "âš ï¸ Plugin file not found at $PLUGIN_FILE"
          fi
          
      - name: Patch All Expo Modules
        script: |
          cd mobile-app
          echo "ðŸ”§ Removing useDefaultAndroidSdkVersions() from all Expo modules..."
          
          # Find all expo-*/android/build.gradle files
          find node_modules/expo-*/android -name "build.gradle" 2>/dev/null | while read file; do
            if grep -q "useDefaultAndroidSdkVersions()" "$file"; then
              echo "Patching: $file"
              # Remove the line
              sed -i.bak '/useDefaultAndroidSdkVersions()/d' "$file"
              rm -f "${file}.bak"
              echo "âœ… Removed useDefaultAndroidSdkVersions() from $file"
            fi
          done
          
          echo "âœ… Finished patching all Expo modules"
          
      - name: Set Gradle Permissions
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
      - name: Build APK
        script: |
          cd mobile-app/android
          ./gradlew assembleRelease --stacktrace --info
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
