workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    cache:
      cache_paths:
        - $CM_BUILD_DIR/mobile-app/node_modules
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install Dependencies
        script: |
          cd mobile-app
          # Use npm install since package-lock.json might be missing
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild to ensure new Gradle config is generated
          npx expo prebuild --platform android --clean
          
      - name: Force AGP 8.1.4 (Expo SDK 51 compatibility)
        script: |
          cd mobile-app/android
          
          echo "📝 Patching build.gradle to force AGP 8.1.4..."
          
          # Backup original
          cp build.gradle build.gradle.backup
          
          # Replace AGP version in buildscript dependencies
          sed -i.bak 's/com.android.tools.build:gradle:[0-9.]\+/com.android.tools.build:gradle:8.1.4/g' build.gradle
          
          echo "✅ Patched AGP version:"
          grep "com.android.tools.build:gradle" build.gradle
          
      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build (SDK 51 + Gradle 8)..."
          
          # Capture both stdout and stderr to log file
          ./gradlew assembleRelease --no-daemon --stacktrace --info > build.log 2>&1
          BUILD_EXIT_CODE=$?
          
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo ""
            echo "❌ BUILD FAILED! AUTOMATIC ERROR REPORT:"
            echo "=============================================================================="
            echo "Build exit code: $BUILD_EXIT_CODE"
            echo "Log file size: $(wc -c < build.log) bytes"
            echo "Log file lines: $(wc -l < build.log) lines"
            echo ""
            
            # Always show the last 150 lines
            echo "Last 150 lines of build output:"
            tail -n 150 build.log
            
            echo "=============================================================================="
            exit 1
          fi
          
          echo "✅ Build succeeded!"
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
      - mobile-app/android/build.log
