workflows:
  android-eas-build:
    name: Android EAS Build (Expo SDK 51)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_TOKEN: $EXPO_TOKEN # Required for EAS authentication
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install --legacy-peer-deps
          
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli@latest
          
      - name: Build with EAS (Local)
        script: |
          cd mobile-app
          
          echo "🚀 Starting EAS Build for Android..."
          echo "Using Expo's managed build system to bypass local Gradle issues"
          
          # Build APK using EAS local build
          eas build --platform android --profile production --local --non-interactive --output=./build.apk
          
          if [ -f "./build.apk" ]; then
            echo "✅ Build succeeded! APK created"
            ls -lh ./build.apk
          else
            echo "❌ Build failed - APK not found"
            exit 1
          fi
          
    artifacts:
      - mobile-app/build.apk
