workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    scripts:
      - name: Install Dependencies & Fix Versions
        script: |
          cd mobile-app
          # Install current package.json dependencies
          npm install --legacy-peer-deps
          
          # Force update Expo dependencies to match SDK 51 requirements
          # This fixes the expo-modules-core incompatibility by pulling the latest patch version
          echo "🔧 Fixing Expo dependency versions..."
          npx expo install --fix
          
          # Verify expo-modules-core version
          echo "📦 Checked expo-modules-core version:"
          npm list expo-modules-core
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild ensures fresh config
          npx expo prebuild --platform android --clean
          
      - name: Build Android APK (Gradle)
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build..."
          
          # Run build using Gradle wrapper
          ./gradlew assembleRelease --no-daemon --stacktrace
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
