workflows:
  android-production-build:
    name: Android Production Build (Expo SDK 51)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        # Memory boost for Gradle 8+
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    scripts:
      - name: Install Dependencies
        script: |
          cd mobile-app
          # Use npm install to ensure all dependencies including expo-modules-core are present
          npm install --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest
          
      - name: Prebuild Android (Generate Native Code)
        script: |
          cd mobile-app
          # Delete old android folder to ensure clean SDK 51 generation
          rm -rf android
          # Clean prebuild ensures fresh config
          npx expo prebuild --platform android --clean
          
      - name: Patch Expo Modules Core (Robust Fix)
        script: |
          cd mobile-app
          
          echo "📝 Searching for buggy ExpoModulesCorePlugin.gradle..."
          # Find all instances of the file in the entire directory
          FOUND_FILES=$(find . -name "ExpoModulesCorePlugin.gradle" -type f)
          
          if [ -z "$FOUND_FILES" ]; then
            echo "❌ Could not find ExpoModulesCorePlugin.gradle anywhere!"
            echo "Listing node_modules/expo-modules-core:"
            ls -R node_modules/expo-modules-core || echo "node_modules/expo-modules-core not found"
            exit 1
          fi
          
          for FILE in $FOUND_FILES; do
            echo "🔧 Patching file: $FILE"
            # create backup
            cp "$FILE" "$FILE.backup"
            # Comment out line 85 (or any line matching the buggy code)
            sed -i.bak 's/from components.release/\/\/ from components.release \/\/ PATCHED BY CI/g' "$FILE"
            echo "✅ Patched $FILE"
            grep "PATCHED BY CI" "$FILE"
          done
          
      - name: Build Android APK (Gradle)
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
          echo "🚀 Starting Gradle Build..."
          
          # Run build using Gradle wrapper
          ./gradlew assembleRelease --no-daemon --stacktrace
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
