workflows:
  android-eas-build:
    name: Android EAS Build (Alternative)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        EXPO_TOKEN: $EXPO_TOKEN # Required for EAS Build
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm ci --legacy-peer-deps
          
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli@latest
          
      - name: Build with EAS (Local)
        script: |
          cd mobile-app
          eas build --platform android --profile production --non-interactive --local --output=./build.apk
          
    artifacts:
      - mobile-app/build.apk
      
    publishing:
      email:
        recipients:
          - $USER_EMAIL
        notify:
          success: true
          failure: true
