workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Fix dependencies
        script: |
          cd mobile-app
          npx expo install --fix
      - name: Install expo-modules-core
        script: |
          cd mobile-app
          npm install expo-modules-core@~1.11.0
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
      - name: Fix Expo Module Plugin
        script: |
          cd mobile-app
          # Verify expo-modules-core is installed
          if [ ! -d "node_modules/expo-modules-core/android" ]; then
            echo "Installing expo-modules-core..."
            npm install expo-modules-core@~1.11.0
          fi
          echo "✅ expo-modules-core verified"
          
      - name: Final Gradle Patch Before Build
        script: |
          echo "Final patching before build..."
          
          # Patch all locations where expo-asset might be
          for path in "node_modules/expo-asset/android/build.gradle" \
                      "mobile-app/node_modules/expo-asset/android/build.gradle" \
                      "/Users/builder/clone/node_modules/expo-asset/android/build.gradle"; do
            if [ -f "$path" ]; then
              echo "Removing useDefaultAndroidSdkVersions() from: $path"
              sed -i '' '/useDefaultAndroidSdkVersions()/d' "$path"
              echo "✅ Patched: $path"
            fi
          done
          
          # Verify patch worked
          if [ -f "node_modules/expo-asset/android/build.gradle" ]; then
            if grep -q "useDefaultAndroidSdkVersions" node_modules/expo-asset/android/build.gradle; then
              echo "⚠️ Warning: useDefaultAndroidSdkVersions still found, trying alternative..."
              # Alternative: comment it out
              sed -i '' 's/useDefaultAndroidSdkVersions()/\/\/ useDefaultAndroidSdkVersions() - removed/g' node_modules/expo-asset/android/build.gradle
            else
              echo "✅ Verified: useDefaultAndroidSdkVersions removed"
            fi
          fi
      - name: Patch Gradle Files
        script: |
          echo "Patching Gradle files..."
          
          # Patch root node_modules (where error occurs)
          if [ -f "node_modules/expo-asset/android/build.gradle" ]; then
            echo "Patching root node_modules/expo-asset/build.gradle..."
            sed -i '' '/useDefaultAndroidSdkVersions()/d' node_modules/expo-asset/android/build.gradle
            if ! grep -q "compileSdkVersion" node_modules/expo-asset/android/build.gradle; then
              sed -i '' '/android {/a\
          compileSdkVersion 34\
          buildToolsVersion "34.0.0"' node_modules/expo-asset/android/build.gradle
            fi
            echo "✅ Patched root expo-asset"
          fi
          
          # Patch mobile-app node_modules
          if [ -f "mobile-app/node_modules/expo-asset/android/build.gradle" ]; then
            echo "Patching mobile-app/node_modules/expo-asset/build.gradle..."
            sed -i '' '/useDefaultAndroidSdkVersions()/d' mobile-app/node_modules/expo-asset/android/build.gradle
            if ! grep -q "compileSdkVersion" mobile-app/node_modules/expo-asset/android/build.gradle; then
              sed -i '' '/android {/a\
          compileSdkVersion 34\
          buildToolsVersion "34.0.0"' mobile-app/node_modules/expo-asset/android/build.gradle
            fi
            echo "✅ Patched mobile-app expo-asset"
          fi
          
          # Also check in clone directory (Codemagic's working directory)
          if [ -f "/Users/builder/clone/node_modules/expo-asset/android/build.gradle" ]; then
            echo "Patching Codemagic clone directory..."
            sed -i '' '/useDefaultAndroidSdkVersions()/d' /Users/builder/clone/node_modules/expo-asset/android/build.gradle
            echo "✅ Patched clone directory expo-asset"
          fi
          
          # Find and patch all expo-asset build.gradle files
          find . -name "build.gradle" -path "*/expo-asset/android/*" 2>/dev/null | while read file; do
            echo "Patching: $file"
            sed -i '' '/useDefaultAndroidSdkVersions()/d' "$file"
          done
      - name: Build APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk

