workflows:
  android-production-build:
    name: Android Production Build - Supplier App
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8"
      node: 20
      java: 17
    scripts:
      - name: Install Mobile App Dependencies (No Workspace)
        script: |
          cd mobile-app
          # Use npm install instead of npm ci to avoid workspace issues
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps --no-workspaces
          # Ensure expo is installed locally
          npm install expo@~50.0.0 --save --legacy-peer-deps --no-workspaces
          # Install @expo/config-plugins for SDK 50 compatibility
          npm install @expo/config-plugins@^7.8.0 --save-dev --legacy-peer-deps --no-workspaces
          # Fix ajv dependency issue - install compatible versions
          npm install ajv@^8.12.0 ajv-keywords@^5.1.0 --save-dev --legacy-peer-deps --no-workspaces
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
          
      - name: Fix Dependencies
        script: |
          cd mobile-app
          npx expo install --fix
          
      - name: Prebuild Android
        script: |
          cd mobile-app
          rm -rf android
          npx expo prebuild --platform android --clean
          # Verify android directory was created
          if [ ! -d "android" ]; then
            echo "ERROR: Android directory was not created by prebuild"
            exit 1
          fi
          
      - name: Build Android APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          # Build with full error output
          ./gradlew assembleRelease --no-daemon --stacktrace --info 2>&1 | tee gradle-build.log || (cat gradle-build.log && exit 1)
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
