workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm ci --legacy-peer-deps
          
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli@latest eas-cli@latest
          
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
          
      - name: Set Gradle Permissions
        script: |
          cd mobile-app/android
          chmod +x gradlew
          
      - name: Build APK
        script: |
          cd mobile-app/android
          ./gradlew assembleRelease --stacktrace --info
          
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
