workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm ci
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Fix dependencies
        script: |
          cd mobile-app
          npx expo install --fix
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
      - name: Build APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace --info
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
