workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_secrets
      vars:
        EXPO_PUBLIC_SUPABASE_URL: $EXPO_PUBLIC_SUPABASE_URL
        EXPO_PUBLIC_SUPABASE_ANON_KEY: $EXPO_PUBLIC_SUPABASE_ANON_KEY
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd mobile-app
          npm ci
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli eas-cli
      - name: Fix dependencies
        script: |
          cd mobile-app
          npx expo install --fix
      - name: Prebuild Android
        script: |
          cd mobile-app
          npx expo prebuild --platform android --clean
      - name: Patch Gradle Files
        script: |
          cd mobile-app
          # Remove problematic useDefaultAndroidSdkVersions
          find . -name "build.gradle" -path "*/expo-asset/android/*" -exec sed -i '' '/useDefaultAndroidSdkVersions()/d' {} \;
          # Add SDK versions if missing
          find . -name "build.gradle" -path "*/expo-asset/android/*" -exec sh -c 'if ! grep -q "compileSdkVersion" "$1"; then sed -i "" "/android {/a\\
          compileSdkVersion 34\\
          buildToolsVersion \"34.0.0\"" "$1"; fi' _ {} \;
      - name: Build APK
        script: |
          cd mobile-app/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - mobile-app/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - $USER_EMAIL
        notify:
          success: true
          failure: true

